# Generated by Django 3.1.4 on 2021-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес отправителя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль от ящика')),
                ('server', models.CharField(default='smtp.gmail.com', max_length=50, verbose_name='Сервер')),
                ('port', models.PositiveSmallIntegerField(default=587, verbose_name='Порт')),
            ],
        ),
    ]
