# Generated by Django 3.1.4 on 2021-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210203_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcredentials',
            name='iban',
            field=models.CharField(default='OU PHOTOBOUTIQUE EE491010220236822220', max_length=70, verbose_name='Реквизиты для оплаты'),
        ),
    ]
