# Generated by Django 3.1.4 on 2021-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_emailcredentials_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Фотография с водянным знаком'),
        ),
    ]
