# Generated by Django 3.1.4 on 2021-02-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210203_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='selling_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография без водяного знака'),
        ),
    ]
