# Generated by Django 3.1.4 on 2021-02-03 23:07

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210204_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='selling_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_origin_upload_to, verbose_name='Фотография без водяного знака'),
        ),
    ]
