# Generated by Django 3.1.4 on 2021-02-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210204_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='FOTOLIFE-SCHOOL', max_length=50, verbose_name='Название компании')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, default='Талин', max_length=25, null=True, verbose_name='Город')),
                ('zip', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Индекс')),
                ('email', models.EmailField(default='fotolife.school@gmail.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='58256779 ', max_length=12, verbose_name='Телефон')),
            ],
        ),
    ]
